spring.application.name=imperio_backend
spring.profiles.active=dev

# ===============================
# = DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/imperio_new
spring.datasource.username=postgres
spring.datasource.password=Rup@@.123$
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect  // auto-detected now
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.session.store-type=none
spring.jpa.open-in-view=false

# ===============================
# = CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# = REQUEST TIMEOUT
# ===============================
spring.mvc.async.request-timeout=60000
server.tomcat.connection-timeout=60000


#==================================================
#= SERVER PROPERITIES CONNECTION
#===================================================
server.port=8080
server.address=0.0.0.0

